update: Fix case statement's indentation

diff --git a/install b/install
--- a/install
+++ b/install
@@ -34,34 +34,32 @@ installer=""
 rcfilepath=""
 
 while (( "$#" )); do
- case "$1" in
+	case "$1" in
+		--branch=*)
+			flag="${1%%=*}"; value="${1#*=}"
+			if [[ -n "$value" ]]; then branch_name="$value"; fi; shift ;;
+		--branch)
+			if [[ -n "$2" && "$2" != *"-" ]]; then branch_name="$2"; fi; shift ;;
 
-	--branch=*)
-		flag="${1%%=*}"; value="${1#*=}"
-		if [[ -n "$value" ]]; then branch_name="$value"; fi; shift ;;
-	--branch)
-		if [[ -n "$2" && "$2" != *"-" ]]; then branch_name="$2"; fi; shift ;;
+		--installer=*)
+			flag="${1%%=*}"; value="${1#*=}"
+			if [[ -n "$value" ]]; then installer="$value"; fi; shift ;;
+		--installer)
+			if [[ -n "$2" && "$2" != *"-" ]]; then installer="$2"; fi; shift ;;
 
-	--installer=*)
-		flag="${1%%=*}"; value="${1#*=}"
-		if [[ -n "$value" ]]; then installer="$value"; fi; shift ;;
-	--installer)
-		if [[ -n "$2" && "$2" != *"-" ]]; then installer="$2"; fi; shift ;;
+		--rcfilepath=*)
+			flag="${1%%=*}"; value="${1#*=}"
+			# Expand `~` in path: [https://stackoverflow.com/a/27485157]
+			if [[ -n "$value" ]]; then rcfilepath="${value/#\~/$HOME}"; fi; shift ;;
+		--rcfilepath)
+			if [[ -n "$2" && "$2" != *"-" ]]; then rcfilepath="$2"; fi; shift ;;
 
-	--rcfilepath=*)
-		flag="${1%%=*}"; value="${1#*=}"
-		# Expand `~` in path: [https://stackoverflow.com/a/27485157]
-		if [[ -n "$value" ]]; then rcfilepath="${value/#\~/$HOME}"; fi; shift ;;
-	--rcfilepath)
-		if [[ -n "$2" && "$2" != *"-" ]]; then rcfilepath="$2"; fi; shift ;;
-
-	--) shift; break ;; # End argument parsing.
-	-*|--*=)
-		# echo "Error: Unsupported flag $1" >&2; exit 1
-		shift ;; # Unsupported flags.
-	*) shift ;; # Preserve positional arguments.
-
-  esac
+		--) shift; break ;; # End argument parsing.
+		-*|--*=)
+			# echo "Error: Unsupported flag $1" >&2; exit 1
+			shift ;; # Unsupported flags.
+		*) shift ;; # Preserve positional arguments.
+	esac
 done
 eval set -- "$params" # Set positional arguments in their proper place
 shift # Remove command from arguments array.
